/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    PrimeButton: typeof import('primevue/button')['default']
    PrimeEditor: typeof import('primevue/editor')['default']
    PrimeFileUpload: typeof import('primevue/fileupload')['default']
    PrimeFloatLabel: typeof import('primevue/floatlabel')['default']
    PrimeInputText: typeof import('primevue/inputtext')['default']
    PrimePanel: typeof import('primevue/panel')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
