import OpenAI from "openai";

// Скелетон из PR: пост пишется о ходе работы над проектом
export interface IPostDraftPr {
	repoName: string | null;
	projectName: string | null;
	projectDescription: string | null;
	commits: string;
}

export interface IPostDraftInput {
	// для темы — заголовок и excerpt поста, для PR — название и описание PR
	title: string;
	excerpt: string;
	lang: string;
	pr?: IPostDraftPr | null;
}

export interface IPostDraft {
	// для PR модель сама придумывает заголовок и excerpt поста,
	// для темы возвращаются присланные
	title: string;
	excerpt: string;
	// html, при сохранении поста проходит через sanitizePostHtml
	content: string;
	readTime: number;
	// base64 без data:-префикса, как его отдаёт images.generate
	imageBase64: string | null;
}

interface ICoverInput {
	title: string;
	excerpt: string;
}

// Пока интеграция не проверена, по умолчанию ходим в мок.
// Реальный запрос включается OPENAI_POST_MOCK=false
const isMockEnabled = () => process.env.OPENAI_POST_MOCK !== "false";

// 1x1 png — достаточно, чтобы прогнать сохранение обложки
const MOCK_IMAGE_BASE64 =
	"iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mNk+M9QDwADhgGAWjR9awAAAABJRU5ErkJggg==";

const mockPostDraft = ({ title, excerpt, pr }: IPostDraftInput): IPostDraft => {
	const project = pr?.projectName || pr?.repoName;

	return {
		title: project ? `${project}: ${title}` : title,
		excerpt,
		content: `<h2>${title}</h2><p>${excerpt}</p>${pr ? `<pre>${pr.commits}</pre>` : ""}<p>This text was generated by the OpenAI mock. Replace it with the real response.</p>`,
		readTime: 3,
		imageBase64: MOCK_IMAGE_BASE64,
	};
};

const DRAFT_TEXT_MODEL = "gpt-5.5";
const DRAFT_IMAGE_MODEL = "gpt-image-2";

// 3:1 — предел gpt-image-2, обе стороны кратны 16. До 1800x500 доводит
// savePostCover, срезая по ~8% сверху и снизу
const DRAFT_IMAGE_SIZE = "1920x640";

const DRAFT_INSTRUCTIONS = `Ты — автор технического блога фронтенд-тимлида с пятилетним опытом (Vue, Nuxt, TypeScript). Пишешь для практикующих разработчиков уровня middle и выше.

Задача: написать статью по заголовку и краткому описанию из сообщения пользователя.

Содержание
- Раскрой ровно то, что обещано в описании, не уходи в смежные темы.
- Пиши от первого лица, по делу, без воды, вступлений вида «в современном мире» и итогов вида «в заключение».
- Объясняй через конкретику: примеры кода, цифры, реальные ситуации из проектов, компромиссы и ограничения.
- Не выдумывай факты, номера версий, API и бенчмарки. Актуальные версии, даты релизов и изменения API проверяй веб-поиском; если подтвердить не удалось — формулируй осторожно или опусти.
- Не вставляй в текст ссылки-сноски на источники и пометки вида «[1]».
- Объём: 900–1400 слов.
- Язык статьи задан кодом lang (ru — русский, en — английский). Термины и названия технологий не переводи.

Структура
- Короткий вводный абзац без заголовка: в чём проблема и что читатель получит.
- 3–5 разделов с заголовками h2, при необходимости подразделы h3.
- Последний раздел — практические выводы: что делать читателю.
- Заголовок статьи в текст не включай, он выводится отдельно.

Разметка поля content
- Только HTML, без Markdown.
- Разрешённые теги: p, h2, h3, ul, ol, li, strong, em, blockquote, pre, code, a.
- Блоки кода: <pre>...</pre>, внутри экранируй < > & как &lt; &gt; &amp;. Короткие идентификаторы в тексте — <code>.
- Без атрибутов class и style, без img, iframe, script, h1.

Поле readTime — целое число минут чтения из расчёта 200 слов в минуту.`;

const PR_INSTRUCTIONS = `Ты пишешь посты для блога на портфолио-сайте фронтенд-разработчика о ходе работы над его pet-проектами. Каждый пост строится строго на одном pull request из сообщения пользователя: название проекта и репозитория, описание проекта, название и описание PR, список коммитов.

Как работать
1. Сначала про себя разбери PR (в ответ этот разбор не попадает):
   - что именно добавлено или изменено и зачем это понадобилось;
   - как изменения улучшили проект;
   - с какими техническими или творческими сложностями пришлось столкнуться;
   - почему обновление может быть интересно читателю.
2. Затем напиши пост по этому разбору.

Правила достоверности
- Опирайся только на данные PR и описание проекта. Не придумывай функции, цифры, библиотеки и проблемы, которых там нет.
- Если коммитов мало и они скупые, напиши короче, а не дофантазируй.
- Версии библиотек и инструментов можешь уточнить веб-поиском. Ссылки-сноски и пометки вида «[1]» в текст не вставляй.
- Описание PR часто содержит шаблон (чек-листы, пустые разделы) — игнорируй его.

Стиль
- Дневник разработчика, от первого лица, дружелюбно и живо.
- Технический жаргон по минимуму, термины поясняй простыми словами.
- Подчёркивай прогресс и личные открытия.
- Объём: 250–400 слов.
- Язык поста задан кодом lang (ru — русский, en — английский). Названия технологий не переводи.

Структура поля content
- Начни с выразительного вступления, упомяни проект.
- 2–4 коротких раздела с заголовками h2 или просто абзацы, если изменений немного; списки — где они помогают.
- Ключевые изменения и сложности выделяй <strong>.
- Заверши планами, мыслью или вопросом к читателям.
- Заголовок поста в content не включай, он выводится отдельно.

Разметка поля content
- Только HTML, без Markdown.
- Разрешённые теги: p, h2, h3, ul, ol, li, strong, em, blockquote, pre, code, a.
- Внутри <pre> экранируй < > & как &lt; &gt; &amp;.
- Без атрибутов class и style, без img, iframe, script, h1.

Остальные поля
- title — заголовок поста до 70 символов: про суть изменений, а не название PR; можно с эмодзи в начале.
- excerpt — 1–2 предложения для карточки поста: что изменилось в проекте и чем это интересно.
- readTime — целое число минут чтения из расчёта 200 слов в минуту.

Пример
Вход:
- Проект: NomadBackpacker
- Название PR: Update PR workflow to integrate server API triggers
- Описание PR: This pull request introduces updates to the PR workflow to utilize the server API for triggering workflows. Additional testing for automatic posting functionality has been included as part of these changes.
- Коммиты: feat: update PR workflow to use server API for trigger

Хороший результат:
title: 🚀 NomadBackpacker: проверки PR теперь запускает сервер
excerpt: Перевёл workflow pull request-ов на серверный API — проверки и автопубликация больше не требуют ручного запуска.
content (сокращённо): <p>Сегодня поработал над «закулисьем» <strong>NomadBackpacker</strong> — обновил workflow для pull request-ов, теперь он запускается через серверный API.</p><p>Раньше PR проверялся вручную или локально — это занимало время. Теперь каждый новый PR автоматически проходит проверку, а автоматическая публикация тоже под контролем тестов.</p><p>Больше всего времени ушло на то, чтобы <strong>workflow запускался гладко</strong> и новые тесты не ломали старые…</p><p>А как вы автоматизируете свои процессы в проектах?</p>`;

const topicInput = ({ title, excerpt, lang }: IPostDraftInput): string =>
	[`Заголовок: ${title}`, `Описание: ${excerpt}`, `lang: ${lang}`].join("\n");

const prInput = ({ title, excerpt, lang, pr }: IPostDraftInput): string =>
	[
		`Проект: ${pr?.projectName || pr?.repoName || "не указан"}`,
		pr?.repoName ? `Репозиторий: ${pr.repoName}` : "",
		pr?.projectDescription
			? `Описание проекта: ${pr.projectDescription}`
			: "",
		`Название PR: ${title}`,
		`Описание PR: ${excerpt || "—"}`,
		`Коммиты:\n${pr?.commits || "—"}`,
		`lang: ${lang}`,
	]
		.filter(Boolean)
		.join("\n");

const coverPrompt = ({ title, excerpt }: ICoverInput): string =>
	[
		`Cover illustration for a frontend engineering blog post titled "${title}".`,
		// описание PR бывает длинным шаблоном, модели картинок хватает начала
		`Post summary: ${excerpt.slice(0, 500)}`,
		"Style: abstract minimal 3D illustration, dark near-black background, soft green accent glow, subtle depth and grain. One clear visual metaphor for the topic instead of a literal screenshot of code or UI.",
		"Composition: ultra-wide panoramic banner, the subject centered with calm background around it; keep a small margin from the top and bottom edges, they will be slightly cropped.",
		"No text, letters, numbers, logos, watermarks, people or faces.",
	].join("\n");

const createClient = (): OpenAI => {
	const apiKey = process.env.OPENAI_KEY;

	if (!apiKey) {
		throw new Error("OPENAI_KEY должен быть задан");
	}

	return new OpenAI({ apiKey });
};

const parseJson = <T>(text: string): Partial<T> => {
	try {
		return JSON.parse(text);
	} catch {
		throw new Error(`OpenAI вернул не JSON: ${text.slice(0, 200)}`);
	}
};

// Общая часть запросов: свежие факты о версиях и релизах модель берёт
// из веб-поиска, а не из памяти
const WEB_SEARCH_REQUEST = {
	model: DRAFT_TEXT_MODEL,
	service_tier: "default",
	reasoning: { mode: "standard", summary: "auto" },
	tools: [
		{
			type: "web_search",
			user_location: { type: "approximate" },
			search_context_size: "medium",
		},
	],
	store: true,
	include: ["reasoning.encrypted_content", "web_search_call.action.sources"],
} satisfies Partial<OpenAI.Responses.ResponseCreateParamsNonStreaming>;

interface IDraftText {
	title?: string;
	excerpt?: string;
	content: string;
	readTime: number;
}

const requestText = async (
	client: OpenAI,
	input: IPostDraftInput,
): Promise<IDraftText> => {
	const isPr = Boolean(input.pr);

	// в strict-режиме required обязан перечислять все поля
	const properties: Record<string, { type: string }> = {
		...(isPr
			? { title: { type: "string" }, excerpt: { type: "string" } }
			: {}),
		content: { type: "string" },
		readTime: { type: "integer" },
	};

	const response = await client.responses.create({
		...WEB_SEARCH_REQUEST,
		instructions: isPr ? PR_INSTRUCTIONS : DRAFT_INSTRUCTIONS,
		input: isPr ? prInput(input) : topicInput(input),
		text: {
			format: {
				type: "json_schema",
				name: "post_draft",
				strict: true,
				schema: {
					type: "object",
					properties,
					required: Object.keys(properties),
					additionalProperties: false,
				},
			},
		},
	});

	const parsed = parseJson<IDraftText>(response.output_text);

	if (!parsed.content) {
		throw new Error("В ответе OpenAI нет content");
	}

	return {
		title: parsed.title,
		excerpt: parsed.excerpt,
		content: parsed.content,
		readTime: Number(parsed.readTime) || 1,
	};
};

const requestCover = async (
	client: OpenAI,
	input: ICoverInput,
): Promise<string | null> => {
	const image = await client.images.generate({
		model: DRAFT_IMAGE_MODEL,
		prompt: coverPrompt(input),
		size: DRAFT_IMAGE_SIZE,
	});

	return image.data?.[0]?.b64_json || null;
};

const requestPostDraft = async (
	input: IPostDraftInput,
): Promise<IPostDraft> => {
	const client = createClient();

	// Для PR обложку рисуем по придуманным заголовку и excerpt: название
	// PR вроде «feat: update workflow» картинке ничего не говорит
	if (input.pr) {
		const text = await requestText(client, input);
		const title = text.title || input.title;
		const excerpt = text.excerpt || input.excerpt;

		return {
			...text,
			title,
			excerpt,
			imageBase64: await requestCover(client, { title, excerpt }),
		};
	}

	const [text, imageBase64] = await Promise.all([
		requestText(client, input),
		requestCover(client, input),
	]);

	return { ...text, title: input.title, excerpt: input.excerpt, imageBase64 };
};

export function fetchPostDraft(input: IPostDraftInput): Promise<IPostDraft> {
	return isMockEnabled()
		? Promise.resolve(mockPostDraft(input))
		: requestPostDraft(input);
}
